# Generated by Django 5.2.5 on 2025-09-10 04:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_id', models.CharField(blank=True, editable=False, max_length=30, unique=True)),
                ('package_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('package_description', models.TextField(blank=True, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sender_name', models.CharField(blank=True, max_length=155, null=True)),
                ('sender_email', models.EmailField(max_length=254)),
                ('sender_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('recipient_name', models.CharField(blank=True, max_length=155, null=True)),
                ('recipient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('destination_phone_number', models.CharField(max_length=20)),
                ('pickup_location', models.CharField(blank=True, max_length=500, null=True)),
                ('destination_location', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('PACKING', 'Packing'), ('EN_ROUTE', 'En Route'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PACKING', max_length=20)),
                ('payment_status', models.BooleanField(default=False)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
