# Generated by Django 5.2.5 on 2025-08-21 12:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_id', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sender_name', models.CharField(blank=True, max_length=155, null=True)),
                ('sender_email', models.EmailField(max_length=254)),
                ('recipient_name', models.CharField(blank=True, max_length=155, null=True)),
                ('sender_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('destination_phone_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('PACKING', 'Packing'), ('EN_ROUTE', 'En Route'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PACKING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('duration', models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('latitude', models.CharField(blank=True, max_length=55, null=True)),
                ('longitude', models.CharField(blank=True, max_length=55, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
