# Generated by Django 5.2.5 on 2025-08-21 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispatch', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_dispatches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rider_dispatches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='destination_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_dispatches', to='dispatch.location'),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='pickup_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_dispatches', to='dispatch.location'),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='package',
            field=models.ManyToManyField(to='dispatch.package'),
        ),
    ]
