# Generated by Django 5.2.5 on 2025-09-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0003_alter_dispatch_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='destination_location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.RemoveField(
            model_name='dispatch',
            name='package',
        ),
        migrations.AddField(
            model_name='dispatch',
            name='package_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='package_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='tracking_id',
            field=models.CharField(blank=True, editable=False, max_length=30, unique=True),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
    ]
