# Generated by Django 5.2.5 on 2025-08-21 13:31

import django.db.models.deletion
import django.utils.timezone
import kyc.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('nin', 'NIN'), ('passport', 'Passport'), ('driver_license', "Driver's License"), ('voter_id', "Voter's ID")], max_length=50)),
                ('document_id', models.CharField(max_length=100, unique=True)),
                ('document', models.FileField(upload_to=kyc.models.upload_kyc_document)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_kyc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC',
                'verbose_name_plural': 'KYC Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
