# Generated by Django 5.2.5 on 2025-09-10 04:36

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=225, unique=True)),
                ('doc_type', models.CharField(choices=[('nin', 'NIN'), ('passport', 'Passport'), ('voter_id', "Voter's ID")], max_length=50)),
                ('document_id', models.CharField(max_length=100)),
                ('licence_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ManyToManyField(related_name='kyc_documents', to='file.file')),
                ('license_document', models.ManyToManyField(related_name='kyc_license_documents', to='file.file')),
            ],
            options={
                'verbose_name': 'KYC',
                'verbose_name_plural': 'KYC Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
