# Generated by Django 5.2.5 on 2025-09-10 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kyc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='kyc',
            constraint=models.UniqueConstraint(fields=('user', 'document_id'), name='unique_doc_per_user'),
        ),
        migrations.AddConstraint(
            model_name='kyc',
            constraint=models.UniqueConstraint(fields=('user', 'licence_id'), name='unique_licence_per_user'),
        ),
    ]
